### ISSUE TITLE
Push Down Automata instruction

### ISSUE THREAD

**Issue by rong-hash** [YihongDong/CODEP#1]
Dear Yihong,

I hope this message finds you well. I recently had the opportunity to delve into your work, and I must say I am genuinely impressed by the depth and insights it offers.

However, I had a few questions regarding a specific aspect that I couldn't find detailed in the paper. Would it be possible for you to provide some guidance or specific instructions on how to construct a PDA for a programming language? I believe this would greatly enhance my understanding and application of your research.

I truly appreciate your time and consideration in addressing my query. Looking forward to your insightful response.

Warm regards,
Zhirong

**Comment by YihongDong** [comment]
Hi Zhirong,
Thanks for your attention. The key to constructing PDA is to use **grammar production rules** to define **transition functions**, referring to the third paragraph of Section 4 in our paper and the previous work [1,2] for details. In addition, we are also building PDAs for other programming languages, which will be released soon.

Best regards,
Yihong Dong

[1] Michael Sipser, [Introduction to the Theory of Computation], PWS Publishing. Section 2.2: Pushdown Automata, pp. 101–114.
[2] Jean-Michel Autebert, Jean Berstel, Luc Boasson, [Context-Free Languages and Push-Down Automata], Handbook of Formal Languages, Vol. 1, Springer-Verlag, 1997, 111–174.
