### ISSUE TITLE
Question about runtime for generation

### ISSUE THREAD

**Issue by hgKang02** [YihongDong/CODEP#2]
Dear Yihong,

I hope this message finds you well. I recently had the opportunity to delve into your work, and I am very impressed by the insights it brings.

However, I have a few questions regarding the time taken for generation. I was trying to run Llama-7b to generate Human-eval dataset and see how it works with Llama models. I tried to run the PDAConstraintSamples folder by using the PDAConstraints for generation. When I try running this, it is taking more than I expected. It takes more than 30 minutes to generate the answer for a single prompt. I believe that this has happened because of my lack of understanding of your code, and mistake during the reproduction. Would it be possible for you to provide me the time taken for generation? Moreover, it will be very helpful if you can provide me the generation time taken for other models such as codeGen and CodeT5 with multi-humaneval dataset.

Just to give you more insight about my problem, below is the prompt from multi-humaneval dataset and also the token that I printed while running the code:

                token_name = self.tokenizer.convert_tokens_to_string(self.tokenizer.convert_ids_to_tokens([token_id]))
                print("Tokens after modification:", token_name)

```
task id is: HumanEval/0
The task id is: HumanEval/0:: prompt is: from typing import List

def has_close_elements(numbers: List[float], threshold: float) -> bool:
        """ Check if in given list of numbers, are any two numbers closer to each other than
        given threshold.
        >>> has_close_elements([1.0, 2.0, 3.0], 0.5)
        False
        >>> has_close_elements([1.0, 2.8, 3.0, 4.0, 5.0, 2.0], 0.3)
        True
        """

Tokens after modification: def
Tokens after modification: NAME
Tokens after modification: (
Tokens after modification: def
Tokens after modification: NAME
Tokens after modification: def
Tokens after modification: def
Tokens after modification: NAME
Tokens after modification: def
Tokens after modification: def
Tokens after modification: NAME
Tokens after modification: (
Tokens after modification: NAME
Tokens after modification: **
Tokens after modification: )
Tokens after modification: *
```

If there is anything that you need from me, please let me know! I truly appreciate your time and consideration in addressing my question!

Sincerely,
Hangoo Kang.

**Comment by YihongDong** [comment]
Dear Hangoo Kang, 
    Do you use https://github.com/YihongDong/CODEP/blob/main/PDAConstraintSample/sample.py or other code (If it is convenient for you to share) to generate it?

Sincerely,
Yihong Dong

**Comment by hgKang02** [comment]
[PDAConstraintSample.zip](https://github.com/YihongDong/CODEP/files/13835567/PDAConstraintSample.zip)

From here, I have used run_llama, eval, and also constraints. I have made some changes because of the format and model difference.

**Comment by YihongDong** [comment]
We recommend using `generation_utils.GenerationMixin.sample = my_generation_utils.GenerationMixin.sample` to generate, and the codes in PDAConstraintSample/backup don't consider the optimization of the sample time. Moreover, we sample codegen350M on MBPP (max_new_tokens = 128, num_return_sequences = 1) using `model.generate` with changing `GenerationMixin.sample`, the average time with PDA constraints is 5.5s/task and the average time w/o PDA constraints is 3.6s/task.

**Comment by hgKang02** [comment]
Thank you so much for your time and consideration!
